#!/usr/bin/env bash
#Installs and configures haproxy
sudo apt-get -y
sudo apt-get -y install haproxy
echo "
frontend http
	 bind *:80
	 mode http
	 default_backend web-backend
 backend web-backend
	 balance roundrobin
	 server 1507-web-01 34.73.113.30:80 check
	 server 1507-web-02 35.185.32.152:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
