#!/usr/bin/env bash
#Installs and configures haproxy
sudo apt-get -y
sudo apt-get -y install haproxy
echo "
frontend http
	 bind *:80
	 mode http
	 default_backend web-backend
 backend web-backend
	 balance roundrobin
	 server 1566-web-01 35.196.104.107:80 check
	 server 1566-web-02 35.243.147.23:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
