#!/usr/bin/env bash
# Scrip that configures an Ubuntu server's local and facebook's host
cp /etc/hosts /etc/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts.new
echo -e "\n8.8.8.8\tfacebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
rm /etc/hosts.new
