#!/usr/bin/env bash
# Configures Nginx to run as Nginx
chmod u+wr,go+r /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -9 -f apache2
sudo -u nginx service nginx restart
