#!/usr/bin/env bash
# Configures Nginx to run as Nginx
pkill -9 apache2
sed -i "s/80/8080/" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
